export {default as Bowser} from "./Bowser.framedata.json"
export {default as CaptainFalcon} from "./Captain Falcon.framedata.json"
export {default as DonkeyKong} from "./Donkey Kong.framedata.json"
export {default as DrMario} from "./Dr Mario.framedata.json"
export {default as Falco} from "./Falco.framedata.json"
export {default as Fox} from "./Fox.framedata.json"
export {default as GameWatch} from "./Game & Watch.framedata.json"
export {default as Ganondorf} from "./Ganondorf.framedata.json"
export {default as Nana} from "./Ice Climbers - Nana.framedata.json"
export {default as Popo} from "./Ice Climbers - Popo.framedata.json"
export {default as Jigglypuff} from "./Jigglypuff.framedata.json"
export {default as Kirby} from "./Kirby.framedata.json"
export {default as Link} from "./Link.framedata.json"
export {default as Luigi} from "./Luigi.framedata.json"
export {default as Mario} from "./Mario.framedata.json"
export {default as Marth} from "./Marth.framedata.json"
export {default as Mewtwo} from "./Mewtwo.framedata.json"
export {default as Ness} from "./Ness.framedata.json"
export {default as Peach} from "./Peach.framedata.json"
export {default as Pichu} from "./Pichu.framedata.json"
export {default as Pikachu} from "./Pikachu.framedata.json"
export {default as Roy} from "./Roy.framedata.json"
export {default as Samus} from "./Samus.framedata.json"
export {default as Sheik} from "./Sheik.framedata.json"
export {default as Yoshi} from "./Yoshi.framedata.json"
export {default as YoungLink} from "./Young Link.framedata.json"
export {default as Zelda} from "./Zelda.framedata.json"